- name: Get Docker convenience script
  ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh

- name: Install Docker
  ansible.builtin.shell: sh get-docker.sh
  args:
    creates: /usr/bin/docker